-- Tạo user
CREATE USER 'admin'@'%' IDENTIFIED BY 'haidang';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'admin1'@'%' IDENTIFIED BY 'thanhle';
GRANT ALL PRIVILEGES ON *.* TO 'admin1'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'admin2'@'%' IDENTIFIED BY 'duytu';
GRANT ALL PRIVILEGES ON *.* TO 'admin2'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'admin3'@'%' IDENTIFIED BY 'dungle';
GRANT ALL PRIVILEGES ON *.* TO 'admin3'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- Tạo database
-- CREATE DATABASE admin_db;
CREATE DATABASE auth_db;
CREATE DATABASE detu_db;
CREATE DATABASE item_db;
CREATE DATABASE user_db;
CREATE DATABASE social_db;
CREATE DATABASE pay_db;
